import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class BookService {
  getBooks(): any[] {
    return [
      {
        ID_genre: '1', ISBN: 'Preety', Name: 'Tiwary',
        Image: 'https://www.gstatic.com/webp/gallery3/1.png',
        Description: 'This is a wider card with supporting text below as a natural lead-in to additional content. Thi wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Ths content is a little bit longer.'
    },
    {
        ID_genre: '1', ISBN: 'Preety', Name: 'Tiwary',
        Image: 'https://www.gstatic.com/webp/gallery3/1.png',
        Description: 'This is a wider card with supporting text below as a natural lead-in to additional content. Thi wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Ths content is a little bit longer.'
    },
    {
        ID_genre: '1', ISBN: 'Preety', Name: 'Tiwary',
        Image: 'https://www.gstatic.com/webp/gallery3/1.png',
        Description: 'This is a wider card with supporting text below as a natural lead-in to additional content. Thi wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Ths content is a little bit longer.'
    },
    {
        ID_genre: '2', ISBN: 'Preety', Name: 'Tiwary',
        Image: 'https://www.gstatic.com/webp/gallery3/1.png',
        Description: 'This is a wider card with supporting text below as a natural lead-in to additional content. Thi wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Ths content is a little bit longer.'
    },
    {
        ID_genre: '2', ISBN: 'Preety', Name: 'Tiwary',
        Image: 'https://www.gstatic.com/webp/gallery3/1.png',
        Description: 'This is a wider card with supporting text below as a natural lead-in to additional content. Thi wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Ths content is a little bit longer.'
    },
    {
        ID_genre: '2', ISBN: 'Preety', Name: 'Tiwary',
        Image: 'https://www.gstatic.com/webp/gallery3/1.png',
        Description: 'This is a wider card with supporting text below as a natural lead-in to additional content. Thi wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Th wider card with supporting text below as a natural lead-in to additional content. Ths content is a little bit longer.'
    },
    ];
  }
}